import { CarClass, Category, Characteristic, Difficulty, type Tune } from "../../../lib/components/forza/types";

export const ALL_TUNES: Tune[] = [
  {
    make: "Toyota",
    model: "GR Yaris",
    year: 2021,
    carClass: CarClass.B,
    category: Category.CC,
    characteristic: Characteristic.HandlingMinus,
    difficulty: Difficulty.Easy,
    tuneId: "TY-GRY-007",
    tuneCreator: "DriftKid",
    comments: "Surprisingly planted, great daily driver feel",
    time: "4:05.221",
  },
  {
    make: "Bugatti",
    model: "Chiron Super Sport",
    year: 2021,
    carClass: CarClass.X,
    category: Category.PrStunt,
    characteristic: Characteristic.PowerPlus,
    difficulty: Difficulty.Hard,
    tuneId: "BG-CSP-001",
    tuneCreator: "TopSpeedFreak",
    comments: "Pure drag monster, zero cornering intent",
    time: "0:58.003",
  },
  {
    make: "Subaru",
    model: "Impreza WRX STI",
    year: 2005,
    carClass: CarClass.A,
    category: Category.Dirt,
    characteristic: Characteristic.HandlingPlus,
    difficulty: Difficulty.Medium,
    tuneId: "SB-WRX-055",
    tuneCreator: "AWDArthur",
    comments: "Classic rally setup, predictable oversteer",
    time: "3:28.777",
  },
  {
    make: "McLaren",
    model: "720S",
    year: 2017,
    carClass: CarClass.S2,
    category: Category.Road,
    characteristic: Characteristic.PowerMinus,
    difficulty: Difficulty.Medium,
    tuneId: "MC-720-019",
    tuneCreator: "BritishSpeedster",
    comments: "Mid-corner stability is superb, light steering",
    time: "2:18.044",
  },
  {
    make: "Volkswagen",
    model: "Golf GTI",
    year: 2021,
    carClass: CarClass.B,
    category: Category.Road,
    characteristic: Characteristic.Balanced,
    difficulty: Difficulty.Easy,
    tuneId: "VW-GTI-033",
    tuneCreator: "HatchbackHero",
    comments: "Great beginner tune, easy to drive fast",
    time: "4:22.115",
  },
  {
    make: "Ferrari",
    model: "488 Pista",
    year: 2019,
    carClass: CarClass.S1,
    category: Category.Road,
    characteristic: Characteristic.PowerMinus,
    difficulty: Difficulty.Hard,
    tuneId: "FR-488-022",
    tuneCreator: "TifosiBoss",
    comments: "Snappy rear but incredibly rewarding when mastered",
    time: "2:05.889",
  },
];
